name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: src
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MESSAGE: "Build: ({sha}) {msg}"
    steps:
      - uses: actions/checkout@v3
      - uses: s0/git-publish-subdir-action@develop
